### ISSUE TITLE
Sleeping can sometimes bypass a Blood Moon

### ISSUE THREAD

**Issue by JasonMcRay** [lumien231/Random-Things#2]
Players are able to bypass Blood Moon by sleeping in bed. It happens almost all the time with beds added by mods, but also sometimes with vanilla bed.

Here are some typical scenarios...some successful, some not.

Quotes from Infitech 2 issue tracker:

> When playing alone on the server, I received the message "The Blood Moon is rising.." I was next to my bed, so I clicked it expecting the message "You don't feel tired right now." I DID get that message, BUT the night skipped nonetheless. I have been able to reliably do this more than once.
> 
> I tried sleeping as No.1 above while other players were on the server and I could NOT skip the night. The Blood Moon happened normally. This scenario reliably happened more than once.
> 
> I tried it ONCE as No.2 above and could NOT skip the Blood Moon. BUT, the other player left the game after a minute or two, so I tried sleeping again. I still received the message "You don't feel tired right now", BUT I was able to skip the Blood Moon.

**Comment by lumien231** [comment]
First of all Random Things for 1.7.10 is no longer getting updates for minor issues like this and this repository is now 1.8 only. If this issue arises again in the Bloodmoon mod for 1.8 feel free to report it there https://github.com/lumien231/Bloodmoon. 

I believe this issue is caused by other mods changing the bed logic and forcibly allowing users to enter beds, as long as this isn't reproduced with only random things / bloodmoon installed i don't kno w how to fix it.
